import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, Building2, House, LogOut, Menu, Search, ShieldCheck, Store, UserRound } from 'lucide-react';
import { createClient, type User } from '@supabase/supabase-js';
import './styles.css';
const supabase = createClient('https://zanyiqoukzanskioivzr.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSI6InphbnlpcW91a3phbnNraW9pdnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2MjI3MDMsImV4cCI6MjA5NzE5ODcwM30.gzEc_rqfApWFdetRyvK0sk3BF3kfiQn72FdNOgkcOVA');
type Role='customer'|'merchant'|'admin'; type Profile={id:string;display_name:string;role:Role};
function Empty({title,detail}:{title:string;detail:string}){return <div className="empty"><Building2 size={30}/><h3>{title}</h3><p>{detail}</p></div>}
function Auth({onUser}:{onUser:(u:Profile)=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.user){alert(error?.message||'تعذر الدخول');setBusy(false);return}const {data:p}=await supabase.from('profiles').select('id,display_name,role').eq('id',data.user.id).single();setBusy(false);if(p)onUser(p as Profile)};return <main className="auth"><div className="hero-visual"><div className="hero-glow"/><div className="hero-building"><span/><span/><span/><span/><span/><span/></div></div><div className="auth-content"><div className="brand-hero"><div className="brand-icon"><House size={20}/></div><div className="brand">جايبلك</div></div><p className="eyebrow">كل ما تحتاجه، أقرب</p><h1>المكان الذي<br/>يشبهك</h1><p>سجّل الدخول للوصول إلى بياناتك الحقيقية ولوحة التحكم المناسبة لدورك.</p><div className="auth-fields"><input placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="كلمة المرور" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary" onClick={()=>void submit()}>{busy?'جارٍ الدخول...':'تسجيل الدخول'}</button></div></div></main>}
function App(){const [user,setUser]=useState<Profile|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{supabase.auth.getSession().then(async({data})=>{if(!data.session){setLoading(false);return}const {data:p}=await supabase.from('profiles').select('id,display_name,role').eq('id',data.session.user.id).single();setUser(p as Profile|null);setLoading(false)})},[]);if(loading)return <main className="auth"><p>جارٍ التحميل...</p></main>;return user?<Dashboard profile={user} onLogout={async()=>{await supabase.auth.signOut();setUser(null)}}/>:<Auth onUser={setUser}/>}
function Dashboard({profile,onLogout}:{profile:Profile;onLogout:()=>void}){const [tab,setTab]=useState('الرئيسية');const [rows,setRows]=useState<Array<{id:string;name:string;category?:string;price?:number}>>([]);const [loading,setLoading]=useState(true);const isMerchant=profile.role==='merchant';const isAdmin=profile.role==='admin';useEffect(()=>{const load=async()=>{if(isMerchant){const {data:c}=await supabase.from('companies').select('id').eq('owner_id',profile.id).maybeSingle();if(c){const {data:p}=await supabase.from('products').select('id,name,category,price').eq('company_id',c.id);setRows((p??[]) as typeof rows)}}else if(isAdmin){const {data:c}=await supabase.from('companies').select('id,name,category').limit(40);setRows((c??[]) as typeof rows)}else{const {data:c}=await supabase.from('companies').select('id,name,category,province,district').limit(40);setRows((c??[]) as typeof rows)}setLoading(false)};void load()},[profile.id,isAdmin,isMerchant]);const title=isAdmin?'لوحة الإدارة':isMerchant?'لوحة التاجر':'جايبلك';return <main className="shell"><header><button className="circle"><Menu size={18}/></button><div className="brand"><House size={18}/> {title}</div><button className="circle"><Bell size={18}/></button></header><section className="intro"><p>مرحباً، {profile.display_name||'بك'}</p><h1>{isAdmin?'إدارة المنصة':isMerchant?'إدارة متجرك':'اكتشف متاجرك المفضلة'}</h1></section>{!isAdmin&&!isMerchant&&<div className="search"><Search size={18}/><input placeholder="ابحث في المتاجر..."/></div>}<div className="chips">{(isAdmin?['نظرة عامة','المتاجر','الحسابات']:isMerchant?['نظرة عامة','المنتجات','الطلبات']:['الرئيسية','استكشف','الرسائل','حسابي']).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{loading?<Empty title="جارٍ تحميل البيانات" detail="يتم جلب البيانات من Supabase."/>:rows.length===0?<Empty title={isMerchant?'لا توجد بيانات متجر':'لا توجد بيانات منشورة'} detail="ستظهر هنا البيانات الحقيقية عند توفرها في قاعدة البيانات."/>:<div className="grid">{rows.map(r=><article className="card" key={r.id}><div className="card-icon">{isAdmin?<ShieldCheck size={20}/>:isMerchant?<Store size={20}/>:<Building2 size={20}/>}</div><h3>{r.name}</h3><p>{r.category||'بدون تصنيف'}</p>{isMerchant&&typeof r.price==='number'&&<strong>{r.price.toLocaleString('ar-IQ')} د.ع</strong>}</article>)}</div>}<nav>{(isAdmin?['نظرة عامة','المتاجر','الحسابات']:isMerchant?['الرئيسية','المنتجات','الطلبات','الإعدادات']:['الرئيسية','استكشف','الرسائل','المفضلة','حسابي']).map(x=><button className={tab===x?'selected':''} onClick={()=>setTab(x)} key={x}><UserRound size={17}/>{x}</button>)}<button onClick={onLogout}><LogOut size={17}/>خروج</button></nav></main>}
createRoot(document.getElementById('root')!).render(<App/>);
