import { useState } from "react";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useI18n } from "@/lib/i18n";
import { BRAND } from "@/constants/brand";
import { getAdminSettings } from "@/lib/admin-settings";

const FAQS = [
  { q: "كيف أضيف منتجاً أو مادة إلى المخزن؟", a: "افتح المنتجات أو المخزن، اضغط إضافة، ثم أدخل البيانات والصورة واحفظ. يمكنك تعديلها أو حذفها لاحقاً مع تأكيد." },
  { q: "كيف أغيّر نوع الحساب؟", a: "من الحساب والملف الشخصي اختر نوع الحساب من القائمة المنسدلة، ثم احفظ التغيير." },
  { q: "كيف أرسل إيصال الإعلان؟", a: "بعد اختيار مدة الإعلان افتح WhatsApp لإرسال تفاصيل الدفع، ثم ارفع صورة الإيصال داخل شاشة الإعلان لمراجعته." },
  { q: "هل بياناتي متصلة بقاعدة حقيقية؟", a: "النسخة الحالية تجريبية محلية. الواجهات والعقود مهيأة للربط الآمن مع Supabase لاحقاً." },
];

export default function HelpSupportScreen() {
  const router = useRouter();
  const colors = useColors();
  const { t } = useI18n();
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const contact = getAdminSettings().contact;
  const openWhatsapp = () => Linking.openURL(`https://wa.me/${contact.whatsappNumber}?text=${encodeURIComponent("مرحباً، أحتاج مساعدة في تاجر")}`);
  const callSupport = () => Linking.openURL(`tel:${contact.supportPhone}`);
  const emailSupport = () => Linking.openURL(`mailto:${contact.supportEmail}`);

  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="arrow-forward" size={20} color={colors.foreground} /></Pressable><View style={styles.header}><Text style={[styles.eyebrow, { color: colors.primary }]}>{BRAND.name}</Text><Text style={[styles.title, { color: colors.foreground }]}>{t("help")}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>نحن هنا لمساعدتك في استخدام تاجر والإجابة عن أسئلتك.</Text></View><View style={[styles.hero, { backgroundColor: colors.foreground }]}><View style={[styles.heroIcon, { backgroundColor: colors.primary }]}><MaterialIcons name="support-agent" size={28} color="#FFFFFF" /></View><View style={styles.heroCopy}><Text style={styles.heroTitle}>كيف نستطيع مساعدتك؟</Text><Text style={styles.heroText}>تصفح الأسئلة الشائعة أو تواصل مع فريق الدعم مباشرة.</Text></View></View><View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>الأسئلة الشائعة</Text><MaterialIcons name="quiz" size={20} color={colors.primary} /></View><View style={styles.faqList}>{FAQS.map((faq, index) => { const open = openFaq === index; return <View key={faq.q} style={[styles.faqCard, { backgroundColor: colors.surface, borderColor: open ? colors.primary : colors.border }]}><Pressable onPress={() => setOpenFaq(open ? null : index)} style={({ pressed }) => [styles.faqQuestion, { opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name={open ? "expand-less" : "expand-more"} size={20} color={colors.primary} /><Text style={[styles.faqQuestionText, { color: colors.foreground }]}>{faq.q}</Text></Pressable>{open && <Text style={[styles.faqAnswer, { color: colors.muted }]}>{faq.a}</Text>}</View>; })}</View><View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>تواصل معنا</Text><MaterialIcons name="headset-mic" size={20} color={colors.primary} /></View><View style={styles.contactGrid}><SupportAction icon="chat" title="WhatsApp" subtitle="أرسل استفسارك مباشرة" color="#25D366" onPress={openWhatsapp} colors={colors} /><SupportAction icon="call" title="اتصال" subtitle={contact.supportPhone} color={colors.primary} onPress={callSupport} colors={colors} /><SupportAction icon="email" title="البريد الإلكتروني" subtitle={contact.supportEmail} color={colors.primary} onPress={emailSupport} colors={colors} /></View><View style={[styles.footerNote, { backgroundColor: `${colors.primary}12`, borderColor: `${colors.primary}35` }]}><MaterialIcons name="schedule" size={18} color={colors.primary} /><Text style={[styles.footerText, { color: colors.foreground }]}>فريق الدعم متاح لمساعدتك، وسيتم إدارة أرقام التواصل من لوحة الإدارة عند الربط الفعلي.</Text></View></ScrollView></ScreenContainer>;
}

function SupportAction({ icon, title, subtitle, color, onPress, colors }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; subtitle: string; color: string; onPress: () => void; colors: ReturnType<typeof useColors> }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.supportCard, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.72 : 1 }]}><View style={[styles.supportIcon, { backgroundColor: `${color}18` }]}><MaterialIcons name={icon} size={20} color={color} /></View><Text style={[styles.supportTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.supportSub, { color: colors.muted }]} numberOfLines={1}>{subtitle}</Text></Pressable>; }

const styles = StyleSheet.create({ content: { flexGrow: 1, padding: 20, paddingBottom: 35 }, back: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, alignItems: "center", justifyContent: "center", alignSelf: "flex-end" }, header: { alignItems: "flex-end", marginTop: 18, marginBottom: 22 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 2 }, title: { fontSize: 30, fontWeight: "900", marginTop: 4 }, subtitle: { fontSize: 11, lineHeight: 19, marginTop: 6, textAlign: "right" }, hero: { minHeight: 112, borderRadius: 24, padding: 16, flexDirection: "row-reverse", alignItems: "center", gap: 12, marginBottom: 24 }, heroIcon: { width: 55, height: 55, borderRadius: 19, alignItems: "center", justifyContent: "center" }, heroCopy: { flex: 1, alignItems: "flex-end" }, heroTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900", textAlign: "right" }, heroText: { color: "rgba(255,255,255,0.75)", fontSize: 10, lineHeight: 17, marginTop: 4, textAlign: "right" }, sectionHeader: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 10, marginTop: 2 }, sectionTitle: { fontSize: 15, fontWeight: "900" }, faqList: { gap: 8, marginBottom: 23 }, faqCard: { borderWidth: 1, borderRadius: 17, overflow: "hidden" }, faqQuestion: { minHeight: 54, paddingHorizontal: 13, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, faqQuestionText: { flex: 1, fontSize: 11, fontWeight: "800", textAlign: "right" }, faqAnswer: { fontSize: 10, lineHeight: 18, textAlign: "right", paddingHorizontal: 13, paddingBottom: 13 }, contactGrid: { gap: 8 }, supportCard: { minHeight: 66, borderRadius: 18, borderWidth: 1, padding: 11, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, supportIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, supportTitle: { width: 115, fontSize: 11, fontWeight: "900", textAlign: "right" }, supportSub: { flex: 1, fontSize: 9, textAlign: "right" }, footerNote: { marginTop: 16, padding: 12, minHeight: 51, borderRadius: 16, borderWidth: 1, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, footerText: { flex: 1, fontSize: 9, lineHeight: 17, textAlign: "right" } });
