import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const FILTERS = ["كل السجلات", "مستحق", "متأخر", "مدفوع"];
const LOGS = [{ id: "1", customer: "أحمد محمد", detail: "دين شراء · اليوم 10:42", amount: "250,000 د.ع", status: "مستحق" }, { id: "2", customer: "سارة علي", detail: "دفعة جزئية · أمس 18:20", amount: "80,000 د.ع", status: "مدفوع" }, { id: "3", customer: "محمد حسن", detail: "دين شراء · 12 آب", amount: "120,000 د.ع", status: "متأخر" }];
export default function DebtSettingsScreen() {
  const router = useRouter(); const colors = useColors();
  const [filter, setFilter] = useState(FILTERS[0]); const [reminders, setReminders] = useState(true); const [notes, setNotes] = useState("تذكير الدفع قبل الاستحقاق بيومين"); const [saving, setSaving] = useState(false);
  const save = () => { setSaving(true); setTimeout(() => { setSaving(false); Alert.alert("تم الحفظ", "تم حفظ إعدادات دفتر الديون محلياً."); }, 650); };
  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="arrow-forward" size={20} color={colors.foreground} /></Pressable><View style={styles.headerCopy}><Text style={[styles.eyebrow, { color: colors.primary }]}>جَايَبْلَك · ERP</Text><Text style={[styles.title, { color: colors.foreground }]}>إعدادات الديون</Text><Text style={[styles.subtitle, { color: colors.muted }]}>سجل واضح لكل عميل ودفعة</Text></View></View>
    <View style={styles.section}><View style={styles.heading}><View style={[styles.icon, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name="filter-list" size={18} color={colors.primary} /></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>فلترة سجل الديون</Text></View><View style={styles.chips}>{FILTERS.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={({ pressed }) => [styles.chip, { backgroundColor: filter === item ? colors.primary : colors.surface, borderColor: filter === item ? colors.primary : colors.border, opacity: pressed ? 0.75 : 1 }]}><Text style={[styles.chipText, { color: filter === item ? colors.foreground : colors.muted }]}>{item}</Text></Pressable>)}</View></View>
    <View style={styles.section}><View style={styles.heading}><View style={[styles.icon, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name="notifications-active" size={18} color={colors.primary} /></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>التذكيرات</Text></View><View style={[styles.toggle, { backgroundColor: colors.surface, borderColor: colors.border }]}><Switch value={reminders} onValueChange={setReminders} trackColor={{ false: colors.border, true: `${colors.primary}88` }} thumbColor={reminders ? colors.primary : colors.muted} /><View style={styles.copy}><Text style={[styles.toggleTitle, { color: colors.foreground }]}>تذكير العملاء بالمستحقات</Text><Text style={[styles.description, { color: colors.muted }]}>يظهر التذكير في سجل العميل قبل موعد الدفع</Text></View></View><Text style={[styles.label, { color: colors.muted }]}>نص التذكير</Text><TextInput value={notes} onChangeText={setNotes} textAlign="right" style={[styles.input, { color: colors.foreground, backgroundColor: colors.background, borderColor: colors.border }]} /></View>
    <View style={styles.section}><View style={styles.heading}><View style={[styles.icon, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name="receipt-long" size={18} color={colors.primary} /></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>سجل الديون والدفعات</Text></View>{LOGS.filter((log) => filter === "كل السجلات" || log.status === filter).map((log) => <View key={log.id} style={[styles.log, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.logBadge, { backgroundColor: log.status === "مدفوع" ? `${colors.success}18` : log.status === "متأخر" ? `${colors.error}18` : `${colors.primary}18` }]}><Text style={[styles.logStatus, { color: log.status === "مدفوع" ? colors.success : log.status === "متأخر" ? colors.error : colors.primary }]}>{log.status}</Text></View><View style={styles.copy}><Text style={[styles.toggleTitle, { color: colors.foreground }]}>{log.customer}</Text><Text style={[styles.description, { color: colors.muted }]}>{log.detail}</Text></View><Text style={[styles.logAmount, { color: colors.foreground }]}>{log.amount}</Text></View>)}</View><View style={[styles.audit, { backgroundColor: `${colors.primary}10`, borderColor: `${colors.primary}35` }]}><MaterialIcons name="history" size={21} color={colors.primary} /><View style={styles.copy}><Text style={[styles.toggleTitle, { color: colors.foreground }]}>سجل العمليات</Text><Text style={[styles.description, { color: colors.muted }]}>سيتم حفظ إضافة الدين والدفعة وتعديلها مع التاريخ والوقت عند الربط الفعلي.</Text></View></View>
    <Pressable disabled={saving} onPress={save} style={({ pressed }) => [styles.save, { backgroundColor: colors.primary, opacity: saving ? 0.7 : pressed ? 0.8 : 1 }]}>{saving ? <ActivityIndicator color={colors.foreground} /> : <MaterialIcons name="check" size={19} color={colors.foreground} />}<Text style={[styles.saveText, { color: colors.foreground }]}>{saving ? "جارٍ حفظ الإعدادات..." : "حفظ إعدادات الديون"}</Text></Pressable>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 38, gap: 21 }, header: { flexDirection: "row-reverse", alignItems: "center", gap: 14 }, back: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, justifyContent: "center", alignItems: "center" }, headerCopy: { flex: 1, alignItems: "flex-end" }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, title: { fontSize: 28, fontWeight: "900", marginTop: 3 }, subtitle: { fontSize: 12, marginTop: 4 }, section: { gap: 12 }, heading: { flexDirection: "row-reverse", alignItems: "center", gap: 9 }, icon: { width: 34, height: 34, borderRadius: 17, justifyContent: "center", alignItems: "center" }, sectionTitle: { fontSize: 17, fontWeight: "900" }, chips: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, chip: { borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 9 }, chipText: { fontSize: 10, fontWeight: "800" }, toggle: { minHeight: 72, borderWidth: 1, borderRadius: 18, paddingHorizontal: 13, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, copy: { flex: 1, alignItems: "flex-end" }, toggleTitle: { fontSize: 13, fontWeight: "900", textAlign: "right" }, description: { fontSize: 10, marginTop: 4, lineHeight: 16, textAlign: "right" }, label: { fontSize: 11, textAlign: "right" }, input: { minHeight: 50, borderWidth: 1, borderRadius: 15, paddingHorizontal: 13, fontSize: 12 }, audit: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, log: { minHeight: 65, borderWidth: 1, borderRadius: 17, padding: 11, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, logBadge: { borderRadius: 9, paddingHorizontal: 8, paddingVertical: 6 }, logStatus: { fontSize: 9, fontWeight: "900" }, logAmount: { fontSize: 11, fontWeight: "900" }, save: { minHeight: 51, borderRadius: 17, flexDirection: "row-reverse", justifyContent: "center", alignItems: "center", gap: 8 }, saveText: { fontSize: 13, fontWeight: "900" } });
