import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const CATEGORIES = ["كل الأصناف", "ملابس", "إلكترونيات", "أطعمة", "تغليف"];

export default function InventorySettingsScreen() {
  const router = useRouter(); const colors = useColors();
  const [category, setCategory] = useState(CATEGORIES[0]); const [prefix, setPrefix] = useState("JBL"); const [lowStock, setLowStock] = useState(true); const [autoHide, setAutoHide] = useState(false); const [saving, setSaving] = useState(false);
  const save = () => { setSaving(true); setTimeout(() => { setSaving(false); Alert.alert("تم الحفظ", "تم حفظ إعدادات المخزون في النسخة التجريبية."); }, 650); };
  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="arrow-forward" size={20} color={colors.foreground} /></Pressable><View style={styles.headerCopy}><Text style={[styles.eyebrow, { color: colors.primary }]}>جَايَبْلَك · ERP</Text><Text style={[styles.title, { color: colors.foreground }]}>إعدادات المخزون</Text><Text style={[styles.subtitle, { color: colors.muted }]}>نظّم أصنافك وأكوادك بسهولة</Text></View></View>
    <Section title="الفئات الافتراضية" icon="category" colors={colors}><View style={styles.chips}>{CATEGORIES.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={({ pressed }) => [styles.chip, { backgroundColor: category === item ? colors.primary : colors.background, borderColor: category === item ? colors.primary : colors.border, opacity: pressed ? 0.75 : 1 }]}><Text style={[styles.chipText, { color: category === item ? colors.foreground : colors.muted }]}>{item}</Text></Pressable>)}</View></Section>
    <Section title="توليد SKU" icon="qr-code" colors={colors}><Text style={[styles.hint, { color: colors.muted }]}>سيضاف هذا الرمز تلقائياً إلى بداية أكواد المنتجات الجديدة.</Text><Text style={[styles.label, { color: colors.muted }]}>بادئة SKU</Text><TextInput value={prefix} onChangeText={(value) => setPrefix(value.toUpperCase().replace(/[^A-Z0-9-]/g, ""))} maxLength={8} textAlign="right" style={[styles.input, { backgroundColor: colors.background, borderColor: colors.border, color: colors.foreground }]} placeholder="JBL" placeholderTextColor={colors.muted} /></Section>
    <Section title="التنبيهات الآلية" icon="notifications-active" colors={colors}><Toggle title="تنبيه الكمية القليلة" description="أرسل تنبيهاً عندما يقترب المنتج من النفاد" value={lowStock} onValueChange={setLowStock} colors={colors} /><Toggle title="إخفاء غير المتوفر" description="أوقف ظهور المنتج للزبائن عند وصول الكمية إلى صفر" value={autoHide} onValueChange={setAutoHide} colors={colors} /></Section>
    <Pressable disabled={saving} onPress={save} style={({ pressed }) => [styles.save, { backgroundColor: colors.primary, opacity: saving ? 0.7 : pressed ? 0.8 : 1 }]}>{saving ? <ActivityIndicator color={colors.foreground} /> : <MaterialIcons name="check" size={19} color={colors.foreground} />}<Text style={[styles.saveText, { color: colors.foreground }]}>{saving ? "جارٍ حفظ الإعدادات..." : "حفظ إعدادات المخزون"}</Text></Pressable>
  </ScrollView></ScreenContainer>;
}
function Section({ title, icon, children, colors }: { title: string; icon: keyof typeof MaterialIcons.glyphMap; children: React.ReactNode; colors: ReturnType<typeof useColors> }) { return <View style={styles.section}><View style={styles.sectionTitle}><View style={[styles.icon, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name={icon} size={18} color={colors.primary} /></View><Text style={[styles.sectionText, { color: colors.foreground }]}>{title}</Text></View>{children}</View>; }
function Toggle({ title, description, value, onValueChange, colors }: { title: string; description: string; value: boolean; onValueChange: (value: boolean) => void; colors: ReturnType<typeof useColors> }) { return <View style={[styles.toggle, { borderColor: colors.border, backgroundColor: colors.background }]}><Switch value={value} onValueChange={onValueChange} trackColor={{ false: colors.border, true: `${colors.primary}88` }} thumbColor={value ? colors.primary : colors.muted} /><View style={styles.toggleCopy}><Text style={[styles.toggleTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.toggleDescription, { color: colors.muted }]}>{description}</Text></View></View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 38, gap: 20 }, header: { flexDirection: "row-reverse", alignItems: "center", gap: 14 }, back: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, justifyContent: "center", alignItems: "center" }, headerCopy: { flex: 1, alignItems: "flex-end" }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, title: { fontSize: 28, fontWeight: "900", marginTop: 3 }, subtitle: { fontSize: 12, marginTop: 4 }, section: { gap: 12 }, sectionTitle: { flexDirection: "row-reverse", gap: 9, alignItems: "center" }, icon: { width: 34, height: 34, borderRadius: 17, justifyContent: "center", alignItems: "center" }, sectionText: { fontSize: 17, fontWeight: "900" }, chips: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, chip: { borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 9 }, chipText: { fontSize: 10, fontWeight: "800" }, hint: { textAlign: "right", fontSize: 11, lineHeight: 18 }, label: { textAlign: "right", fontSize: 11 }, input: { minHeight: 49, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontSize: 14, fontWeight: "800" }, toggle: { minHeight: 70, borderWidth: 1, borderRadius: 18, paddingHorizontal: 13, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, toggleCopy: { flex: 1, alignItems: "flex-end" }, toggleTitle: { fontSize: 13, fontWeight: "900" }, toggleDescription: { fontSize: 10, marginTop: 4, textAlign: "right" }, save: { minHeight: 51, borderRadius: 17, flexDirection: "row-reverse", justifyContent: "center", alignItems: "center", gap: 8 }, saveText: { fontSize: 13, fontWeight: "900" } });
