import { useState } from "react";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { LANGUAGES, useI18n, type Language } from "@/lib/i18n";
import { useThemeContext } from "@/lib/theme-provider";
import type { ColorScheme } from "@/constants/theme";

export default function LanguageAppearanceScreen() {
  const router = useRouter();
  const colors = useColors();
  const { language, setLanguage, t, direction } = useI18n();
  const { colorScheme, setColorScheme } = useThemeContext();
  const [saved, setSaved] = useState(false);

  const chooseLanguage = (next: Language) => { setLanguage(next); showSaved(); };
  const chooseTheme = (next: ColorScheme) => { setColorScheme(next); showSaved(); };
  const showSaved = () => { setSaved(true); setTimeout(() => setSaved(false), 1500); };
  const languageDescription = (code: Language) => code === "ar" ? t("arabicInterface") : code === "ku" ? t("kurdishInterface") : t("englishInterface");

  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name={direction === "rtl" ? "arrow-forward" : "arrow-back"} size={20} color={colors.foreground} /></Pressable><View style={styles.header}><Text style={[styles.eyebrow, { color: colors.primary }]}>{t("settings")}</Text><Text style={[styles.title, { color: colors.foreground }]}>{t("language")}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{t("languageSubtitle")}</Text></View><SectionTitle icon="language" title={t("appLanguageTitle")} colors={colors} /><View style={styles.languageList}>{LANGUAGES.map((item) => <Pressable key={item.code} onPress={() => chooseLanguage(item.code)} style={({ pressed }) => [styles.languageCard, { backgroundColor: colors.surface, borderColor: language === item.code ? colors.primary : colors.border, opacity: pressed ? 0.72 : 1 }]}><View style={[styles.radio, { borderColor: language === item.code ? colors.primary : colors.border }]}>{language === item.code && <View style={[styles.radioDot, { backgroundColor: colors.primary }]} />}</View><View style={styles.optionCopy}><Text style={[styles.optionTitle, { color: colors.foreground }]}>{item.label}</Text><Text style={[styles.optionSub, { color: colors.muted }]}>{languageDescription(item.code)}</Text></View><Text style={[styles.short, { color: language === item.code ? colors.primary : colors.muted }]}>{item.short}</Text></Pressable>)}</View><SectionTitle icon="brightness-6" title={t("appAppearance")} colors={colors} /><View style={styles.themeRow}><ThemeCard icon="wb-sunny" title={t("lightTheme")} selected={colorScheme === "light"} onPress={() => chooseTheme("light")} colors={colors} /><ThemeCard icon="dark-mode" title={t("darkTheme")} selected={colorScheme === "dark"} onPress={() => chooseTheme("dark")} colors={colors} /></View>{saved && <View style={[styles.saved, { backgroundColor: `${colors.success}14` }]}><MaterialIcons name="check-circle" size={17} color={colors.success} /><Text style={[styles.savedText, { color: colors.success }]}>{t("selectionSaved")}</Text></View>}<View style={[styles.note, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialIcons name="info-outline" size={18} color={colors.primary} /><Text style={[styles.noteText, { color: colors.muted }]}>{t("changeAnytime")}</Text></View></ScrollView></ScreenContainer>;
}

function SectionTitle({ icon, title, colors }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; colors: ReturnType<typeof useColors> }) { return <View style={styles.sectionTitle}><View style={[styles.sectionIcon, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name={icon} size={18} color={colors.primary} /></View><Text style={[styles.sectionText, { color: colors.foreground }]}>{title}</Text></View>; }
function ThemeCard({ icon, title, selected, onPress, colors }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; selected: boolean; onPress: () => void; colors: ReturnType<typeof useColors> }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.themeCard, { backgroundColor: colors.surface, borderColor: selected ? colors.primary : colors.border, opacity: pressed ? 0.72 : 1 }]}><View style={[styles.themeIcon, { backgroundColor: selected ? colors.primary : colors.background }]}><MaterialIcons name={icon} size={21} color={selected ? "#FFFFFF" : colors.primary} /></View><Text style={[styles.themeTitle, { color: colors.foreground }]}>{title}</Text>{selected && <MaterialIcons name="check-circle" size={19} color={colors.primary} />}</Pressable>; }

const styles = StyleSheet.create({ content: { flexGrow: 1, padding: 20, paddingBottom: 35 }, back: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, alignItems: "center", justifyContent: "center", alignSelf: "flex-end" }, header: { alignItems: "flex-end", marginTop: 18, marginBottom: 24 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 2 }, title: { fontSize: 30, fontWeight: "900", marginTop: 4 }, subtitle: { fontSize: 11, lineHeight: 19, marginTop: 6, textAlign: "right", maxWidth: 430 }, sectionTitle: { flexDirection: "row-reverse", alignItems: "center", gap: 8, marginBottom: 10, marginTop: 4 }, sectionIcon: { width: 35, height: 35, borderRadius: 12, alignItems: "center", justifyContent: "center" }, sectionText: { fontSize: 15, fontWeight: "900" }, languageList: { gap: 8 }, languageCard: { minHeight: 70, borderWidth: 1, borderRadius: 19, padding: 12, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, radio: { width: 21, height: 21, borderRadius: 11, borderWidth: 2, alignItems: "center", justifyContent: "center" }, radioDot: { width: 11, height: 11, borderRadius: 6 }, optionCopy: { flex: 1, alignItems: "flex-end" }, optionTitle: { fontSize: 13, fontWeight: "900" }, optionSub: { fontSize: 9, marginTop: 4, textAlign: "right" }, short: { width: 28, fontSize: 13, fontWeight: "900", textAlign: "center" }, themeRow: { flexDirection: "row-reverse", gap: 10 }, themeCard: { flex: 1, minHeight: 90, borderWidth: 1, borderRadius: 20, padding: 12, alignItems: "center", justifyContent: "center", gap: 7 }, themeIcon: { width: 39, height: 39, borderRadius: 14, alignItems: "center", justifyContent: "center" }, themeTitle: { fontSize: 12, fontWeight: "900" }, saved: { marginTop: 16, minHeight: 43, borderRadius: 14, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 7 }, savedText: { fontSize: 11, fontWeight: "800" }, note: { marginTop: 16, minHeight: 50, borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, noteText: { flex: 1, fontSize: 10, textAlign: "right", lineHeight: 17 } });
