import { useEffect, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const SEED = [
  { id: "1256", customer: "أحمد محمد", total: "250,000 د.ع", status: "جديد", date: "اليوم، 10:42" },
  { id: "1255", customer: "سارة علي", total: "180,000 د.ع", status: "قيد التجهيز", date: "اليوم، 09:18" },
  { id: "1254", customer: "محمد حسن", total: "75,000 د.ع", status: "تم التسليم", date: "أمس، 18:25" },
];
const STATUSES = ["جديد", "قيد التجهيز", "جاهز للشحن", "تم التسليم", "ملغى"];

export default function OrdersScreen() {
  const colors = useColors();
  const router = useRouter();
  const [orders, setOrders] = useState(SEED);
  useEffect(() => { AsyncStorage.getItem("jabilak-orders").then((value) => { if (value) setOrders(JSON.parse(value)); }).catch(() => undefined); }, []);
  const updateStatus = (id: string, status: string) => { const next = orders.map((order) => order.id === id ? { ...order, status } : order); setOrders(next); void AsyncStorage.setItem("jabilak-orders", JSON.stringify(next)); };
  const newCount = orders.filter((order) => order.status === "جديد").length;
  const activeCount = orders.filter((order) => order.status === "قيد التجهيز" || order.status === "جاهز للشحن").length;
  const deliveredCount = orders.filter((order) => order.status === "تم التسليم").length;
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={orders} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialIcons name="arrow-forward" size={20} color={colors.foreground} /></Pressable><View style={styles.copy}><Text style={[styles.kicker, { color: colors.primary }]}>إدارة المبيعات</Text><Text style={[styles.title, { color: colors.foreground }]}>الطلبات</Text><Text style={[styles.subtitle, { color: colors.muted }]}>راجع الطلبات وحدث حالتها للعميل</Text></View><View style={[styles.icon, { backgroundColor: colors.primary }]}><MaterialIcons name="receipt-long" size={21} color="#FFFFFF" /></View></View><View style={styles.summaryStrip}><OrderSummary label="جديد" value={newCount} color={colors.primary} colors={colors} icon="fiber-new" /><OrderSummary label="قيد التنفيذ" value={activeCount} color={colors.warning} colors={colors} icon="pending-actions" /><OrderSummary label="تم التسليم" value={deliveredCount} color={colors.success} colors={colors} icon="check-circle" /></View></>} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.row}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={styles.avatarText}>{item.customer.slice(0, 1)}</Text></View><View style={styles.info}><View style={styles.top}><Text style={[styles.customer, { color: colors.foreground }]}>{item.customer}</Text><Text style={[styles.id, { color: colors.muted }]}>#{item.id}</Text></View><View style={styles.top}><Text style={[styles.date, { color: colors.muted }]}>{item.date}</Text><Text style={[styles.total, { color: colors.primary }]}>{item.total}</Text></View></View></View><Text style={[styles.label, { color: colors.muted }]}>حالة الطلب</Text><View style={styles.statusRow}>{STATUSES.map((status) => <Pressable key={status} onPress={() => updateStatus(item.id, status)} style={({ pressed }) => [styles.status, { backgroundColor: item.status === status ? colors.primary : colors.background, borderColor: item.status === status ? colors.primary : colors.border, opacity: pressed ? 0.7 : 1 }]}><Text style={[styles.statusText, { color: item.status === status ? "#FFFFFF" : colors.foreground }]}>{status}</Text></Pressable>)}</View><Pressable onPress={() => Alert.alert(`الطلب #${item.id}`, `العميل: ${item.customer}\nالقيمة: ${item.total}\nالحالة: ${item.status}`)} style={styles.details}><Text style={[styles.detailsText, { color: colors.primary }]}>عرض تفاصيل الطلب</Text><MaterialIcons name="arrow-back" size={16} color={colors.primary} /></Pressable></View>} ListEmptyComponent={<Text style={[styles.empty, { color: colors.muted }]}>لا توجد طلبات حالياً</Text>} /></ScreenContainer>;
}
function OrderSummary({ label, value, color, colors, icon }: { label: string; value: number; color: string; colors: ReturnType<typeof useColors>; icon: keyof typeof MaterialIcons.glyphMap }) { return <View style={[styles.summaryCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.summaryIcon, { backgroundColor: `${color}18` }]}><MaterialIcons name={icon} size={16} color={color} /></View><Text style={[styles.summaryValue, { color: colors.foreground }]}>{value}</Text><Text style={[styles.summaryLabel, { color: colors.muted }]}>{label}</Text></View>; }

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 40, gap: 12 }, header: { flexDirection: "row-reverse", alignItems: "center", gap: 11, marginBottom: 8 }, summaryStrip: { flexDirection: "row-reverse", gap: 8, marginBottom: 12 }, summaryCard: { flex: 1, minHeight: 82, borderRadius: 17, borderWidth: 1, padding: 10, alignItems: "flex-end" }, summaryIcon: { width: 28, height: 28, borderRadius: 10, alignItems: "center", justifyContent: "center", marginBottom: 5 }, summaryValue: { fontSize: 17, fontWeight: "900" }, summaryLabel: { fontSize: 8, marginTop: 1 }, back: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, alignItems: "flex-end" }, kicker: { fontSize: 11, fontWeight: "900" }, title: { fontSize: 28, fontWeight: "900", marginTop: 2 }, subtitle: { fontSize: 11, marginTop: 4 }, icon: { width: 43, height: 43, borderRadius: 15, alignItems: "center", justifyContent: "center" }, card: { borderRadius: 21, borderWidth: 1, padding: 15, gap: 10 }, row: { flexDirection: "row-reverse", alignItems: "center", gap: 10 }, avatar: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, info: { flex: 1, gap: 8 }, top: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, customer: { fontSize: 13, fontWeight: "900" }, id: { fontSize: 10 }, date: { fontSize: 9 }, total: { fontSize: 12, fontWeight: "900" }, label: { textAlign: "right", fontSize: 10, fontWeight: "800", marginTop: 2 }, statusRow: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 6 }, status: { borderWidth: 1, borderRadius: 11, paddingHorizontal: 9, paddingVertical: 7 }, statusText: { fontSize: 9, fontWeight: "800" }, details: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 6, paddingTop: 3 }, detailsText: { fontSize: 10, fontWeight: "900" }, empty: { textAlign: "center", padding: 30 } });

/* البيانات محلية في المعاينة؛ يستبدل Repository هذا المصدر عند ربط Supabase. */
 void 0;
