import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";

import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const CATEGORIES = ["الكل", "ملابس", "إلكترونيات", "أطعمة", "أثاث", "خدمات"];
const PROVINCES = ["كل المحافظات", "بغداد", "البصرة", "أربيل", "النجف", "كربلاء", "دهوك", "السليمانية"];
const DISTRICTS = ["كل المناطق", "الكرادة", "المنصور", "الجادرية", "الأعظمية", "العشار"];
const STORE_TYPES = ["الكل", "شركة", "متجر محلي", "موزع", "متجر منزلي"];
const SORTS = ["الأكثر صلة", "الأحدث", "الأعلى تقييماً", "الأكثر مبيعاً"];

export default function SearchFiltersScreen() {
  const colors = useColors();
  const router = useRouter();
  const [category, setCategory] = useState("الكل");
  const [province, setProvince] = useState("كل المحافظات");
  const [district, setDistrict] = useState("كل المناطق");
  const [storeType, setStoreType] = useState("الكل");
  const [rating, setRating] = useState("كل التقييمات");
  const [sort, setSort] = useState("الأكثر صلة");
  const [verified, setVerified] = useState(false);
  const [available, setAvailable] = useState(false);
  const [minPrice, setMinPrice] = useState(0);
  const [maxPrice, setMaxPrice] = useState(500000);
  const [provinceOpen, setProvinceOpen] = useState(false);
  const [districtOpen, setDistrictOpen] = useState(false);
  const [typeOpen, setTypeOpen] = useState(false);
  const [sortOpen, setSortOpen] = useState(false);

  const reset = () => { setCategory("الكل"); setProvince("كل المحافظات"); setDistrict("كل المناطق"); setStoreType("الكل"); setRating("كل التقييمات"); setSort("الأكثر صلة"); setVerified(false); setAvailable(false); setMinPrice(0); setMaxPrice(500000); setProvinceOpen(false); setDistrictOpen(false); setTypeOpen(false); setSortOpen(false); };
  const apply = () => { Alert.alert("تم تطبيق الفلاتر", `${category} · ${province} · ${minPrice.toLocaleString("en-US")}–${maxPrice.toLocaleString("en-US")} د.ع`, [{ text: "عرض النتائج", onPress: () => router.replace("/explore") }]); };

  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="arrow-forward" size={20} color={colors.foreground} /></Pressable><View style={styles.heading}><Text style={[styles.title, { color: colors.foreground }]}>فلترة البحث</Text><Text style={[styles.subtitle, { color: colors.muted }]}>حدّد تفضيلاتك للوصول إلى النتيجة المناسبة</Text></View></View>
    <Section title="الفئة" colors={colors}><View style={styles.chips}>{CATEGORIES.map((item) => <Chip key={item} label={item} active={category === item} onPress={() => setCategory(item)} colors={colors} />)}</View></Section>
    <Section title="الموقع" colors={colors}><Select label="المحافظة" value={province} open={provinceOpen} onPress={() => { setProvinceOpen((value) => !value); setDistrictOpen(false); }} colors={colors} />{provinceOpen && <OptionList items={PROVINCES} selected={province} onSelect={(value) => { setProvince(value); setProvinceOpen(false); }} colors={colors} />}<Select label="المنطقة" value={district} open={districtOpen} onPress={() => { setDistrictOpen((value) => !value); setProvinceOpen(false); }} colors={colors} />{districtOpen && <OptionList items={DISTRICTS} selected={district} onSelect={(value) => { setDistrict(value); setDistrictOpen(false); }} colors={colors} />}</Section>
    <Section title="نطاق السعر" colors={colors}><View style={styles.priceHeader}><Text style={[styles.priceValue, { color: colors.primary }]}>{maxPrice.toLocaleString("en-US")} د.ع</Text><Text style={[styles.priceValue, { color: colors.primary }]}>{minPrice.toLocaleString("en-US")} د.ع</Text></View><RangeSlider min={minPrice} max={maxPrice} onChange={(nextMin, nextMax) => { setMinPrice(nextMin); setMaxPrice(nextMax); }} colors={colors} /><View style={styles.priceLabels}><Text style={[styles.rangeLabel, { color: colors.muted }]}>500,000 د.ع</Text><Text style={[styles.rangeLabel, { color: colors.muted }]}>0 د.ع</Text></View></Section>
    <Section title="التقييم" colors={colors}><View style={styles.chips}>{["كل التقييمات", "4 نجوم فأعلى", "3 نجوم فأعلى", "نجمتان فأعلى"].map((item) => <Chip key={item} label={item} active={rating === item} onPress={() => setRating(item)} colors={colors} icon="star" />)}</View></Section>
    <Section title="خيارات إضافية" colors={colors}><Toggle label="الشركات الموثقة فقط" icon="verified" value={verified} onPress={() => setVerified((value) => !value)} colors={colors} /><Toggle label="المنتجات المتوفرة فقط" icon="inventory-2" value={available} onPress={() => setAvailable((value) => !value)} colors={colors} /><Select label="نوع المتجر" value={storeType} open={typeOpen} onPress={() => { setTypeOpen((value) => !value); setSortOpen(false); }} colors={colors} />{typeOpen && <OptionList items={STORE_TYPES} selected={storeType} onSelect={(value) => { setStoreType(value); setTypeOpen(false); }} colors={colors} />}</Section>
    <Section title="ترتيب النتائج" colors={colors}><Select label="طريقة الترتيب" value={sort} open={sortOpen} onPress={() => { setSortOpen((value) => !value); setTypeOpen(false); }} colors={colors} />{sortOpen && <OptionList items={SORTS} selected={sort} onSelect={(value) => { setSort(value); setSortOpen(false); }} colors={colors} />}</Section>
    <View style={styles.actions}><Pressable onPress={reset} style={({ pressed }) => [styles.resetButton, { borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><Text style={[styles.resetText, { color: colors.foreground }]}>إعادة تعيين</Text></Pressable><Pressable onPress={apply} style={({ pressed }) => [styles.applyButton, { backgroundColor: colors.primary, opacity: pressed ? 0.76 : 1 }]}><Text style={styles.applyText}>تطبيق الفلاتر</Text><MaterialIcons name="arrow-back" size={18} color="#FFFFFF" /></Pressable></View><View style={{ height: 35 }} /></ScrollView></ScreenContainer>;
}

function Section({ title, children, colors }: { title: string; children: React.ReactNode; colors: ReturnType<typeof useColors> }) { return <View style={[styles.section, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{title}</Text>{children}</View>; }
function Chip({ label, active, onPress, colors, icon }: { label: string; active: boolean; onPress: () => void; colors: ReturnType<typeof useColors>; icon?: "star" }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.chip, { backgroundColor: active ? colors.primary : colors.background, borderColor: active ? colors.primary : colors.border, opacity: pressed ? 0.68 : 1 }]}>{icon && <MaterialIcons name="star" size={13} color={active ? "#FFFFFF" : colors.warning} />}<Text style={[styles.chipText, { color: active ? "#FFFFFF" : colors.foreground }]}>{label}</Text></Pressable>; }
function Select({ label, value, open, onPress, colors }: { label: string; value: string; open: boolean; onPress: () => void; colors: ReturnType<typeof useColors> }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.select, { borderColor: open ? colors.primary : colors.border, backgroundColor: colors.background, opacity: pressed ? 0.74 : 1 }]}><MaterialIcons name={open ? "keyboard-arrow-up" : "keyboard-arrow-down"} size={20} color={colors.primary} /><View style={styles.selectText}><Text style={[styles.selectLabel, { color: colors.muted }]}>{label}</Text><Text style={[styles.selectValue, { color: colors.foreground }]}>{value}</Text></View></Pressable>; }
function OptionList({ items, selected, onSelect, colors }: { items: string[]; selected: string; onSelect: (value: string) => void; colors: ReturnType<typeof useColors> }) { return <View style={[styles.optionList, { borderColor: colors.border, backgroundColor: colors.background }]}>{items.map((item) => <Pressable key={item} onPress={() => onSelect(item)} style={[styles.optionRow, { borderBottomColor: colors.border }]}><Text style={[styles.optionText, { color: item === selected ? colors.primary : colors.foreground }]}>{item}</Text>{item === selected && <MaterialIcons name="check" size={17} color={colors.primary} />}</Pressable>)}</View>; }
function Toggle({ label, icon, value, onPress, colors }: { label: string; icon: keyof typeof MaterialIcons.glyphMap; value: boolean; onPress: () => void; colors: ReturnType<typeof useColors> }) { return <Pressable onPress={onPress} style={[styles.toggle, { borderColor: value ? colors.primary : colors.border, backgroundColor: value ? `${colors.primary}10` : colors.background }]}><MaterialIcons name={value ? "check-circle" : "radio-button-unchecked"} size={19} color={value ? colors.primary : colors.muted} /><Text style={[styles.toggleText, { color: colors.foreground }]}>{label}</Text><MaterialIcons name={icon} size={18} color={colors.primary} /></Pressable>; }
function RangeSlider({ min, max, onChange, colors }: { min: number; max: number; onChange: (min: number, max: number) => void; colors: ReturnType<typeof useColors> }) { const [active, setActive] = useState<"min" | "max">("max"); const range = 500000; const update = (x: number) => { const value = Math.max(0, Math.min(range, Math.round((1 - x / 330) * range / 10000) * 10000)); if (active === "min") onChange(Math.min(value, max - 10000), max); else onChange(min, Math.max(value, min + 10000)); }; return <View style={styles.sliderWrap} onStartShouldSetResponder={() => true} onResponderGrant={(event) => { const x = event.nativeEvent.locationX; setActive(Math.abs(x - (1 - min / range) * 330) < Math.abs(x - (1 - max / range) * 330) ? "min" : "max"); update(x); }} onResponderMove={(event) => update(event.nativeEvent.locationX)}><View style={[styles.track, { backgroundColor: colors.border }]} /><View style={[styles.trackActive, { backgroundColor: colors.primary, right: `${(min / range) * 100}%`, left: `${(1 - max / range) * 100}%` }]} /><View style={[styles.knob, { backgroundColor: colors.primary, right: `${(min / range) * 100}%` }]} /><View style={[styles.knob, { backgroundColor: colors.primary, left: `${(1 - max / range) * 100}%` }]} /></View>; }

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 30 }, header: { flexDirection: "row-reverse", alignItems: "center", gap: 12, marginBottom: 20 }, heading: { flex: 1, alignItems: "flex-end" }, title: { fontSize: 27, fontWeight: "900" }, subtitle: { fontSize: 11, marginTop: 4, textAlign: "right" }, iconButton: { width: 43, height: 43, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center" }, section: { borderWidth: 1, borderRadius: 21, padding: 14, marginBottom: 12 }, sectionTitle: { fontSize: 15, fontWeight: "900", textAlign: "right", marginBottom: 12 }, chips: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, chip: { minHeight: 37, borderWidth: 1, borderRadius: 13, paddingHorizontal: 11, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 4 }, chipText: { fontSize: 10, fontWeight: "800" }, select: { minHeight: 55, borderWidth: 1, borderRadius: 16, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 }, selectText: { alignItems: "flex-end" }, selectLabel: { fontSize: 9 }, selectValue: { fontSize: 12, fontWeight: "800", marginTop: 3 }, optionList: { borderWidth: 1, borderRadius: 15, overflow: "hidden", marginBottom: 8 }, optionRow: { minHeight: 39, paddingHorizontal: 12, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1 }, optionText: { fontSize: 11, fontWeight: "700" }, priceHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, priceValue: { fontSize: 12, fontWeight: "900" }, sliderWrap: { height: 34, marginTop: 12, justifyContent: "center", position: "relative" }, track: { height: 6, borderRadius: 3, position: "absolute", left: 4, right: 4, top: 14 }, trackActive: { height: 6, borderRadius: 3, position: "absolute", top: 14 }, knob: { width: 20, height: 20, borderRadius: 10, position: "absolute", top: 7, borderWidth: 4, borderColor: "#FFFFFF", shadowColor: "#000000", shadowOpacity: 0.12, shadowRadius: 3, elevation: 2 }, priceLabels: { flexDirection: "row", justifyContent: "space-between" }, rangeLabel: { fontSize: 9 }, toggle: { minHeight: 49, borderWidth: 1, borderRadius: 15, paddingHorizontal: 12, flexDirection: "row-reverse", alignItems: "center", gap: 8, marginBottom: 8 }, toggleText: { flex: 1, textAlign: "right", fontSize: 11, fontWeight: "800" }, actions: { flexDirection: "row-reverse", gap: 10, marginTop: 7 }, resetButton: { flex: 1, height: 50, borderRadius: 16, borderWidth: 1, alignItems: "center", justifyContent: "center" }, resetText: { fontSize: 12, fontWeight: "800" }, applyButton: { flex: 1.5, height: 50, borderRadius: 16, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8 }, applyText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" } });
