import { useMemo, useState } from "react";
import { Alert, ImageBackground, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { REAL_IMAGES } from "@/constants/assets";
import { BRAND } from "@/constants/brand";

const PRODUCTS = {
  "p-1": { name: "قميص كلاسيك", category: "ملابس وأزياء", price: 45000, previous: 55000, quantity: 34, description: "قميص بقصة عصرية وخامة مريحة للاستخدام اليومي.", options: "أسود، أبيض · S, M, L, XL", tone: "#81B7EC", image: REAL_IMAGES.products.shirt, icon: "checkroom" as const },
  "p-2": { name: "جاكيت رسمي", category: "ملابس وأزياء", price: 85000, previous: 99000, quantity: 4, description: "جاكيت أنيق للمناسبات والعمل.", options: "كحلي، رمادي · M, L, XL", tone: "#655B77", image: REAL_IMAGES.products.suit, icon: "dry-cleaning" as const },
  "p-3": { name: "مجموعة الشتاء", category: "ملابس وأزياء", price: 120000, previous: 0, quantity: 0, description: "مجموعة شتوية متكاملة بتصميم عملي.", options: "أسود · M, L", tone: "#443C50", image: REAL_IMAGES.products.bag, icon: "ac-unit" as const },
  "p-4": { name: "حزام جلدي", category: "ملابس وأزياء", price: 28000, previous: 0, quantity: 18, description: "حزام جلدي طبيعي بلمسة بسيطة.", options: "بني، أسود · مقاس موحد", tone: "#968A98", image: REAL_IMAGES.products.watch, icon: "style" as const },
  "p-5": { name: "حقيبة عملية", category: "ملابس وأزياء", price: 65000, previous: 0, quantity: 8, description: "حقيبة عملية واسعة للاستخدام اليومي.", options: "بيج، أسود", tone: "#1A1821", image: REAL_IMAGES.products.bag, icon: "work-outline" as const },
};

type Product = (typeof PRODUCTS)[keyof typeof PRODUCTS];
const format = (value: number) => `${value.toLocaleString("en-US")} د.ع`;

export default function ProductDetailScreen() {
  const colors = useColors(); const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>();
  const product: Product = useMemo(() => PRODUCTS[id as keyof typeof PRODUCTS] ?? PRODUCTS["p-1"], [id]);
  const [quantity, setQuantity] = useState(1); const [saved, setSaved] = useState(false);
  const available = product.quantity > 0;
  const addToCart = () => { if (!available) { Alert.alert("غير متوفر", "سيظهر المنتج مجدداً عند توفر كمية جديدة."); return; } Alert.alert("أضيف إلى السلة", `${product.name} × ${quantity} أضيف إلى سلتك التجريبية.`); };
  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="arrow-forward" size={20} color={colors.foreground} /></Pressable><View style={styles.headerActions}><Pressable onPress={() => setSaved((value) => !value)} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name={saved ? "favorite" : "favorite-border"} size={20} color={saved ? colors.error : colors.foreground} /></Pressable><Pressable onPress={() => Share.share({ message: `${product.name} عبر ${BRAND.name}` })} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="share" size={19} color={colors.foreground} /></Pressable></View></View>
    <View style={[styles.cover, { backgroundColor: product.tone }]}><ImageBackground source={{ uri: product.image }} style={StyleSheet.absoluteFillObject} /><View style={styles.coverOverlay} /><View style={styles.orb} /><MaterialIcons name={product.icon} size={70} color="rgba(255,255,255,0.82)" /><View style={[styles.status, { backgroundColor: available ? `${colors.success}E8` : `${colors.error}E8` }]}><Text style={styles.statusText}>{available ? `متوفر · ${product.quantity}` : "غير متوفر"}</Text></View></View>
    <View style={styles.copy}><Text style={[styles.category, { color: colors.primary }]}>{product.category}</Text><Text style={[styles.title, { color: colors.foreground }]}>{product.name}</Text><View style={styles.rating}><MaterialIcons name="star" size={18} color={colors.warning} /><Text style={[styles.ratingText, { color: colors.foreground }]}>4.8</Text><Text style={[styles.reviews, { color: colors.muted }]}>(32 تقييم)</Text></View><View style={styles.priceRow}><Text style={[styles.price, { color: colors.primary }]}>{format(product.price)}</Text>{product.previous > 0 && <Text style={[styles.previous, { color: colors.muted }]}>{format(product.previous)}</Text>}</View></View>
    <View style={[styles.infoCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>عن المنتج</Text><Text style={[styles.description, { color: colors.muted }]}>{product.description}</Text><View style={[styles.divider, { backgroundColor: colors.border }]}><Text style={[styles.optionLabel, { color: colors.muted }]}>الخيارات المتاحة</Text><Text style={[styles.options, { color: colors.foreground }]}>{product.options}</Text></View></View>
    <View style={styles.bottomRow}><View style={[styles.quantity, { backgroundColor: colors.surface, borderColor: colors.border }]}><Pressable disabled={!available || quantity >= Math.max(product.quantity, 1)} onPress={() => setQuantity((value) => value + 1)}><MaterialIcons name="add" size={20} color={available ? colors.primary : colors.muted} /></Pressable><Text style={[styles.quantityText, { color: colors.foreground }]}>{quantity}</Text><Pressable disabled={quantity <= 1} onPress={() => setQuantity((value) => Math.max(1, value - 1))}><MaterialIcons name="remove" size={20} color={quantity > 1 ? colors.primary : colors.muted} /></Pressable></View><Pressable onPress={addToCart} style={({ pressed }) => [styles.cartButton, { backgroundColor: available ? colors.primary : colors.border, opacity: pressed ? 0.8 : 1 }]}><MaterialIcons name="shopping-bag" size={19} color={available ? colors.foreground : colors.muted} /><Text style={[styles.cartText, { color: available ? colors.foreground : colors.muted }]}>{available ? "أضف إلى السلة" : "غير متوفر حالياً"}</Text></Pressable></View>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32, gap: 16 }, header: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, headerActions: { flexDirection: "row-reverse", gap: 8 }, iconButton: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, alignItems: "center", justifyContent: "center" }, cover: { height: 286, borderRadius: 28, alignItems: "center", justifyContent: "center", overflow: "hidden" }, coverOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(17,17,17,0.32)" }, orb: { position: "absolute", width: 260, height: 260, borderRadius: 130, right: -72, bottom: -100, backgroundColor: "rgba(255,255,255,0.14)" }, status: { position: "absolute", top: 14, right: 14, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 12 }, statusText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, copy: { alignItems: "flex-end" }, category: { fontSize: 11, fontWeight: "800" }, title: { fontSize: 28, fontWeight: "900", marginTop: 5 }, rating: { flexDirection: "row-reverse", alignItems: "center", gap: 5, marginTop: 9 }, ratingText: { fontSize: 12, fontWeight: "900" }, reviews: { fontSize: 10 }, priceRow: { flexDirection: "row-reverse", alignItems: "baseline", gap: 8, marginTop: 12 }, price: { fontSize: 20, fontWeight: "900" }, previous: { fontSize: 11, textDecorationLine: "line-through" }, infoCard: { borderWidth: 1, borderRadius: 22, padding: 16, gap: 10 }, sectionTitle: { fontSize: 17, fontWeight: "900", textAlign: "right" }, description: { fontSize: 12, lineHeight: 20, textAlign: "right" }, divider: { height: 1, marginVertical: 3 }, optionLabel: { fontSize: 10, textAlign: "right", marginTop: 9 }, options: { fontSize: 12, textAlign: "right", marginTop: 4, fontWeight: "800" }, bottomRow: { flexDirection: "row-reverse", gap: 10 }, quantity: { minWidth: 112, height: 52, borderWidth: 1, borderRadius: 17, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-around" }, quantityText: { fontSize: 15, fontWeight: "900" }, cartButton: { flex: 1, minHeight: 52, borderRadius: 17, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 7 }, cartText: { fontSize: 12, fontWeight: "900" } });
